const products = [
  {
    id: 01,
    name: "Air Jordan 1 - in orange for men",
    image: "./images/pic-1.webp",
    brand: "Nike brand",
    rating: 4.5,
    price: 150,
    new: true,
  },
  {
    id: 02,
    name: "Air Jordan 1 - in yellow",
    image: "./images/pic-2.webp",
    brand: "Nike brand",
    rating: 4.2,
    price: 138,
    new: true,
  },
  {
    id: 03,
    name: " PUMA Carina – Dynamic And Youthful",
    image: "./images/pic-3.webp",
    brand: "Puma brand",
    rating: 4.0,
    price: 175,
    new: true,
  },
  {
    id: 04,
    name: " Reebok Club C85 – Walking, everyday wear",
    image: "./images/pic-4.webp",
    brand: "Reebok brand",
    rating: 3.9,
    price: 105,
    new: true,
  },
  {
    id: 05,
    name: " Reebok Men's Ex-o-fit - Hi Sneaker",
    image: "./images/pic-5.webp",
    brand: "Reebok brand",
    rating: 4.0,
    price: 199,
    new: true,
  },
  {
    id: 06,
    name: "Air Jordan 1 – Walking, everyday wear",
    image: "./images/pic-6.webp",
    brand: "Nike brand",
    rating: 3.6,
    price: 175,
    new: true,
  },
];
